### ISSUE TITLE
Ace Zero comparison

### ISSUE THREAD

**Issue by phongnhhn92** [hwanhuh/Radiance-Fields-from-VGGSfM-Mast3r#1]
Hi,

Thanks for this wonderful repo ! I wonder if you can use ACE Zero to estimate the camera pose and then use 2D-GS to reconstruct the scene. I would love to see the comparison between Master, VGGSFM and ACE Zero on the problem of pose estimation.

**Comment by hwanhuh** [comment]
Hi,

Thanks for your support!

Using ACE Zero for camera pose estimation followed by 2D-GS for scene reconstruction is a great idea. 
I plan to compare the pose estimation performance of Master, VGGSFM, and ACE Zero.

I'll update the results as soon as possible.

Best regards,

**Comment by hwanhuh** [comment]
@phongnhhn92 
Hi, 
I ran ACE0 on the same datasets used in this repo. Unfortunately, ACE0 fails to reconstruct camera poses with the default settings.

![pen_sparse_ace0_mapping](https://github.com/user-attachments/assets/b9389f19-2054-4b57-b102-ab96a948c64e)
![guitar_ace0_mapping](https://github.com/user-attachments/assets/ad97904e-6754-42db-82c8-ac38de5f7850)

I’ve reached out to the authors regarding settings for sparse inputs and will update if I receive a response.

**Comment by phongnhhn92** [comment]
Thanks ! I would love to know more. I am surprised to see that AceZero fails on your sparse captured sequence. I wonder if the method only works if the input frames has high similarity, meaning those frames are continuously extracted from a video.

**Comment by hwanhuh** [comment]
Frames are extracted from a video (captured in a hand-held camera).

**Comment by phongnhhn92** [comment]
Hmm, can you try again with a longer sequence ? I mean 6 images might not work but what about 60 frames perhaps.

**Comment by hwanhuh** [comment]
I tried to reduce the confidence according to the official author's answer ([ace0 issue #6](https://github.com/nianticlabs/acezero/issues/6)), but it still does not converge.

In my opinion, Ace0, VGGSfM, and MASt3R each exhibit a clear trade-off relationship.

From MASt3R and VGGSfM to ACE0, the number of images that can be processed increases, but the convergence speed improves. The main advantage of ACE0 seems to be its ability to perform camera pose reconstruction (as well as pointcloud) in a reasonable time for datasets with abundant overlap.

However, sparse view scenarios perform significantly better for MASt3R and VGGSfM.

On the one hand, for achieving good reconstruction performance in sparse views with VGGSfM, please refer to [issue #2's discussion](https://github.com/hwanhuh/Radiance-Fields-from-VGGSfM-Mast3r/issues/2#issuecomment-2250524764).

Best regards,
