### ISSUE TITLE
using vggsfm pose as initial to input mast3r

### ISSUE THREAD

**Issue by cv-lab-x** [hwanhuh/Radiance-Fields-from-VGGSfM-Mast3r#3]
hi, thanks for your great work, dust3r and mast3r can input inital poses.

**Comment by hwanhuh** [comment]
Hi, @cv-lab-x 

Thank you for your question and interest in this work.

I think integrating VGGSfM poses as initial inputs for MASt3R presents some challenges:

- **Coordinate Alignment**: VGGSfM and MASt3R are optimized differently, requiring the alignment of MASt3R to the coordinate space of VGGSfM.
- **Point Cloud Density**: The differing densities of the point clouds necessitate careful alignment of the estimated camera poses to ensure similarity.
- **Pose Noise**: MASt3R's reconstructed poses can be noisy. Even with optimal alignment to VGGSfM's poses, pointcloud distribution and pose accuracy discrepancies may persist. As noted, MASt3R's angular distance error can be nessesity.

Further Optimization: To mitigate these issues, additional camera pose optimization, as outlined in the repository, would be necessary.

Best regards,

**Comment by hwanhuh** [comment]
Hi @cv-lab-x ,

Sorry for the previous reply, I misunderstood the issue.

Currently, only Dust3r supports the feature of reconstructing from known cameras. For more details, please refer to this [link](https://github.com/naver/mast3r/issues/6).

I will test your suggestion if this feature becomes supported in the future.

Best regards,
